Threadpool
anstkras/Java-Homework pull request #10
Opened 2019-05-01 00:30 UTC by anstkras

2019-05-04 22:07 UTC, RamSaw requested changes
@anstkras домашку проверил.

2019-05-04 22:07 UTC, RamSaw commented on ThreadPool/src/main/java/ru/hse/anstkras/threadpool/ThreadPool.java
> +    private volatile boolean isShutDown = false;
зачем volatile?

2019-05-04 22:07 UTC, RamSaw commented on ThreadPool/src/main/java/ru/hse/anstkras/threadpool/ThreadPool.java
> +            thread.interrupt();
join тоже лучше писать. Знак хорошего тона так скажем.

2019-05-04 22:07 UTC, RamSaw commented on ThreadPool/src/main/java/ru/hse/anstkras/threadpool/ThreadPool.java
> +        return threadsNumber;
если это для теста используется, то это плохой тест, потому что надо по факту проверять, что потоки есть в опреационной системе.

2019-05-04 22:07 UTC, RamSaw commented on ThreadPool/build.gradle
> +plugins {
у меня build 7 минут шел. зависает на тесте. видимо у Вас дедлок.

2019-05-04 22:07 UTC, RamSaw commented on ThreadPool/src/main/java/ru/hse/anstkras/threadpool/ThreadPool.java
> +                            throw new LightExecutionException(exception);
это должно быть ignored. Это spurious wakeup.

2019-05-04 22:07 UTC, RamSaw commented on ThreadPool/src/main/java/ru/hse/anstkras/threadpool/ThreadPool.java
> +                        } catch (InterruptedException ignored) {
тут нужна проверка. а вдруг мы интеррапнулись, потому что shutdown.

2019-05-04 22:07 UTC, RamSaw commented on ThreadPool/src/main/java/ru/hse/anstkras/threadpool/ThreadPool.java
> +            ThreadPoolTask task = null;
null redundant.

2019-05-04 22:07 UTC, RamSaw commented on ThreadPool/src/test/java/ru/hse/anstkras/threadpool/ThreadPoolTest.java
> +    void simpleTestForOneThread() {
тесты можно повторять несколько раз. давайте так сделаем, чтобы было хоть какое-то нагрузочное тестирование.

2019-05-04 22:07 UTC, RamSaw commented on ThreadPool/src/test/java/ru/hse/anstkras/threadpool/ThreadPoolTest.java
> +        assertDoesNotThrow(() -> {
а почему в этих тестах есть assertDoesNotThrow, а в других нет. По какому принципу Вы их выбираете?

2019-05-04 22:07 UTC, RamSaw commented on ThreadPool/src/test/java/ru/hse/anstkras/threadpool/ThreadPoolTest.java
> +            final int SIZE = 100;
стайлгайд, -0.5

2019-05-04 22:07 UTC, RamSaw commented on ThreadPool/src/main/java/ru/hse/anstkras/threadpool/ThreadPool.java
> +        public <T> LightFuture<T> thenApply(@NotNull Function<? super R, T> function) {
ThenApply не должен работать, если shutdown вызван.

2019-05-04 22:07 UTC, RamSaw commented on ThreadPool/src/test/java/ru/hse/anstkras/threadpool/ThreadPoolTest.java
> +    void threadPoolHasNThreads() {
не, это плохой тест. вообще тесты со временем всегда плохи. они ненадежны. в некоторых случаях можно смириться, но не в этом.

2019-05-04 22:07 UTC, RamSaw commented on ThreadPool/build.gradle
> +plugins {
добавьте стресс тестирование как раз. Если проявиться то и хорошо, если нет, то тоже хорошо. Мб при первом билде в градле что-то пошло не так

2019-05-05 05:52 UTC, jzuken commented on ThreadPool/src/test/java/ru/hse/anstkras/threadpool/ThreadPoolTest.java
> +            final int SIZE = 100;
а что не так? константа вроде

2019-05-05 09:32 UTC, RamSaw commented on ThreadPool/src/test/java/ru/hse/anstkras/threadpool/ThreadPoolTest.java
> +            final int SIZE = 100;
Так она же локальная. Обычно же final int myVariable пишем. А static int MY_VARIABLE. 
Oracle пишет немного смутно, но вроде только про статические говорит: 
The names of variables declared class  constants and of ANSI constants should be all uppercase with words separated by under- scores (“_”). (ANSI constants should be avoided, for ease of debugging.)

2019-05-14 15:04 UTC, anstkras commented on ThreadPool/src/main/java/ru/hse/anstkras/threadpool/ThreadPool.java
> +    private volatile boolean isShutDown = false;
Ну вдруг каким-то другим потокам интересно, работает еще threadpool или нет

2019-05-14 15:05 UTC, anstkras commented on ThreadPool/src/main/java/ru/hse/anstkras/threadpool/ThreadPool.java
> +        return threadsNumber;
Это просто глупый тест на геттер, по сути

2019-05-14 19:56 UTC, anstkras commented on ThreadPool/src/test/java/ru/hse/anstkras/threadpool/ThreadPoolTest.java
> +        assertDoesNotThrow(() -> {
Теперь исключения убраны в сигнатуры методов

2019-05-14 21:31 UTC, anstkras commented
@RamSaw , замечания исправлены

2019-05-16 15:29 UTC, RamSaw commented on ThreadPool/src/main/java/ru/hse/anstkras/threadpool/ThreadPool.java
> +    private volatile boolean isShutDown = false;
не, я про то зачем этой переменной нужен volatile модификатор.

2019-05-16 16:02 UTC, RamSaw requested changes
@anstkras Так а Вы смогли воспроизвести deadlock? 
Как я понял Вы ввели Object lock и решили лочиться на нем. 
Но я не нашел ошибки в предыдущем удаленном коде, Вы нашли?

2019-05-16 16:02 UTC, RamSaw commented on ThreadPool/src/main/java/ru/hse/anstkras/threadpool/ThreadPool.java
> +    public void shutdown() throws InterruptedException {
мы наверное хотим заджойнить в итоге оставшиеся потоки, поэтому InterruptedExcpetion стоит игнорировать.
Вообще InterruptedException означает не "прервись немедленно", а "завершись если можешь или когда будешь готов".

2019-05-16 16:02 UTC, RamSaw commented on ThreadPool/src/main/java/ru/hse/anstkras/threadpool/ThreadPool.java
> +            tasks.notifyAll();
а чем был плох просто notify? кажется, что мы разбудим только ждущие потоки, а значит лучше разбудить только один какой-то, потому что только он сможет взять это задание.

2019-05-16 16:02 UTC, RamSaw commented on ThreadPool/src/test/java/ru/hse/anstkras/threadpool/ThreadPoolTest.java
> +    void testIsShutDown() throws InterruptedException {
ну они кидаться не должны, но я это уже выше написал

2019-05-16 16:02 UTC, RamSaw commented on ThreadPool/src/main/java/ru/hse/anstkras/threadpool/ThreadPool.java
> +                    addTaskToQueue(task);
я бы вынес это из synchrinized. у вас же еще внутри там лок есть.

2019-05-22 22:57 UTC, anstkras commented on ThreadPool/src/main/java/ru/hse/anstkras/threadpool/ThreadPool.java
> +    private volatile boolean isShutDown = false;
Чтобы если она стала true, какие-то другие потоки смогли это сразу увидеть

2019-05-22 22:58 UTC, anstkras commented on ThreadPool/src/main/java/ru/hse/anstkras/threadpool/ThreadPool.java
> +            tasks.notifyAll();
Случайно оставила `notifyAll`, исправлено

2019-05-22 23:05 UTC, anstkras commented
Deadlock'и появлялись при неоднократном запуске почти любых тестов на `thenApply`, ошибка была в том, что "дети" конкретной задачи добавлялись в очередь готовых на исполнение раньше, чем у этой задачи ставился `isReady=true`. Сделала один `lock`, потому что так код кажется понятнее, к тому же, в старой версии при 82-ом повторении теста `simpleTestForManyThreads` все падает с исключением `java.lang.OutOfMemoryError: unable to create native thread: possibly out of memory or process/resource limits reached` и я не очень знаю, почему.

2019-05-22 23:13 UTC, anstkras commented
@RamSaw , замечания исправлены

2019-05-26 20:41 UTC, RamSaw approved these changes
@anstkras все ок. 
@jzuken

2019-06-06 07:25 UTC, jzuken commented
конфликт с мастером

2019-06-06 07:29 UTC, merged