Cannon
anstkras/Java-Homework pull request #12
Opened 2019-05-22 03:12 UTC by anstkras

2019-05-30 19:09 UTC, RamSaw requested changes
@anstkras проверил. Если бы Вы написали хотя бы один тест, то архитектура была бы полностью другая. Потому что сейчас ни один юнит тест на логику игры не написать. Разбейте, пожалуйста, код на классы и сущности и уберите все неименованные константы. Код читать и понимать очень сложно.

2019-05-30 19:09 UTC, RamSaw commented on Cannon/build.gradle
> +mainClassName = 'ru.hse.anstkras.cannon.Cannon'
jar не запускается

2019-05-30 19:09 UTC, RamSaw commented on Cannon/settings.gradle
> +rootProject.name = 'Cannon'
В целом о игре:
тяжелый снаряд летит дальше, чем более легкий :) 
у Вас не лагает полет снаряда? А, то у меня что-то он подлагивает

2019-05-30 19:09 UTC, RamSaw commented on Cannon/src/main/java/ru/hse/anstkras/cannon/Cannon.java
> +package ru.hse.anstkras.cannon;
один файл? не ну давайте разобьем для приличия. файл на 400 строчек это перебор

2019-05-30 19:09 UTC, RamSaw commented on Cannon/src/main/java/ru/hse/anstkras/cannon/Cannon.java
> +        segmentsList.add(new Segment(2, 650, HEIGHT - 300, 776.92, HEIGHT - 46.154));
46.154? Я не очень понял, что такое segment и зачем он нужен, начав читать код. Давайте генерацию ландшафта вынесим в отдельный метод (или мб даже класс) и внутри него еще методов создадим, чтобы было сразу понятно, что происходит. первый параметр это тангенс, но зачем вам тогда две точки. Прямая задается же либо 2 точками, либо углом и точкой. И кажется если вы построили mountain, то две прямых из этого треугольника можно высчитать и не хардкодить числа.

2019-05-30 19:09 UTC, RamSaw commented on Cannon/src/main/java/ru/hse/anstkras/cannon/Cannon.java
> +                    rectangleRotate.setAngle(0);
какой смысл этой строчки, если в updateRotate он меняется?

2019-05-30 19:09 UTC, RamSaw commented on Cannon/src/main/java/ru/hse/anstkras/cannon/Cannon.java
> +            rectangleRotate.setAngle(0);
и этой,

2019-05-30 19:09 UTC, RamSaw commented on Cannon/src/main/java/ru/hse/anstkras/cannon/Cannon.java
> +            rectangleRotate.setAngle(rectangleAngle);
эти три последние строчки это код updateRotate()

2019-05-30 19:09 UTC, RamSaw commented on Cannon/src/main/java/ru/hse/anstkras/cannon/Cannon.java
> +        private final static int STEP = 10; // step for x coordinate for each frame
у вас дальше в коде захардкожена эта 10. Давайте все константы вынесим в именованные переменные и будет использовать только их. И комменты джавадоковские лучше, чем //

2019-05-30 19:09 UTC, RamSaw commented on Cannon/src/main/java/ru/hse/anstkras/cannon/Cannon.java
> +        CannonBallType(int radius, int length, double curve, double space) {
что значит радиус у шара (ball), я понимаю, а вот все остальное не очень. Давайте комменты напишем.

2019-05-30 19:09 UTC, RamSaw commented on Cannon/src/main/java/ru/hse/anstkras/cannon/Cannon.java
> +        private Circle circle = new Circle(125, HEIGHT - 125, CIRCLE_RADIUS);
125 очень странное число. В общем давайте откажемся от всех захардкоженных констант. Оставим только -1, 0, 1. Все остальные сделаем именованными. Главное непонятно, у вас же шар должен нарисоваться на горе, а значит под этими цифрами лежат расчеты. Так вот их надо написать в коде, чтобы поменяв ландшафт немного ничего бы не поехало.

2019-05-30 19:09 UTC, RamSaw commented on Cannon/src/main/java/ru/hse/anstkras/cannon/Cannon.java
> +            // compute coefficient of parabola
коммент не нужен будет, если вынести это все в функцию

2019-05-30 19:09 UTC, RamSaw commented on Cannon/src/main/java/ru/hse/anstkras/cannon/Cannon.java
> +                        bullet.setCenterY((coefficient * x * x) + startY - length * length * coefficient);
код очень трудно понять. Магическое число 5 непонятно вообще. Я пытался сопоставить с уравнением параболы, получающийся из физики хоть как-то, но не получилось. Давайте этот код вынесем и как-нибудь объясним. И заодно пофиксим, что более тяжелый снаряд летит дальше (наверное у большей массы должна быть начальная скорость меньше, поэтому он пролетит меньше).

2019-05-30 19:09 UTC, RamSaw commented on Cannon/src/main/java/ru/hse/anstkras/cannon/Cannon.java
> +            return (point1.getX() - point3.getX()) * (point2.getY() - point3.getY()) - (point2.getX() - point3.getX()) * (point1.getY() - point3.getY());
строчка слишком длинная.

2019-05-30 19:09 UTC, RamSaw commented on Cannon/src/main/java/ru/hse/anstkras/cannon/Cannon.java
> +            return (point1.getX() - point3.getX()) * (point2.getY() - point3.getY()) - (point2.getX() - point3.getX()) * (point1.getY() - point3.getY());
А что значит знак между 3 точками?

2019-06-09 09:04 UTC, RamSaw commented
@anstkras а где ваш PR с FtpGUI? На hwproj отмечено, что вы сдали эту домашку.

2019-06-10 08:19 UTC, jzuken commented
9 баллов

2019-06-10 08:19 UTC, merged