MyJUnit
anstkras/Java-Homework pull request #14
Opened 2019-06-02 16:43 UTC by anstkras

2019-06-07 19:37 UTC, jzuken requested changes

2019-06-07 19:37 UTC, jzuken commented on MyJUnit/src/main/java/ru/hse/anstkras/myjunit/Test.java
> +    Class exception() default DefaultException.class;
а тут тоже доки бы не помешали
-0.5

2019-06-07 19:37 UTC, jzuken commented on MyJUnit/src/main/java/ru/hse/anstkras/myjunit/Tester.java
> +            throw new MyJUnitException("No accessible constructor with no parameters", exception);
а обычный JUnit тоже исключениями кидается, когда что-то идёт не так?

2019-06-07 19:37 UTC, jzuken commented on MyJUnit/src/main/java/ru/hse/anstkras/myjunit/Tester.java
> +            if (method.getAnnotation(Test.class) != null) {
а хорошо бы ещё проверить, что на метод не навесили больше, чем надо. ну и какие-нибудь BeforeClass наверняка хотят статический метод, что тоже хорошо бы проверить

2019-06-07 19:37 UTC, jzuken commented on MyJUnit/src/test/java/ru/hse/anstkras/myjunit/ClassDoesNotThrow.java
> +public class ClassDoesNotThrow {
я бы их в отдельный пакет положил, чтобы не мешались

2019-06-08 10:45 UTC, anstkras commented on MyJUnit/src/main/java/ru/hse/anstkras/myjunit/Tester.java
> +            if (method.getAnnotation(Test.class) != null) {
Почему BeforeClass хочет статический метод? Junit одинаково работает как со статическими, так и не со статическими

2019-06-08 10:48 UTC, anstkras commented on MyJUnit/src/main/java/ru/hse/anstkras/myjunit/Tester.java
> +            throw new MyJUnitException("No accessible constructor with no parameters", exception);
Кажется, да, например, если `@BeforeAll` не у статического метода написать

2019-06-08 11:17 UTC, anstkras commented on MyJUnit/src/main/java/ru/hse/anstkras/myjunit/Tester.java
> +            if (method.getAnnotation(Test.class) != null) {
Сделала, чтобы `@BeforeClass` и `@AfterClass` требовали static methods, а остальные аннотации - не static methods. Что значит, навесить больше, чем нужно? Кажется, что вешать на метод одновременно `@Test` и `@After` вполне законно. А повесить `@BeforeClass` и `@Test` теперь не получится из-за требований к static

2019-06-10 08:34 UTC, merged