Hw2
anstkras/Java-Homework pull request #2
Opened 2019-01-28 11:30 UTC by anstkras

2019-02-02 22:43 UTC, RamSaw requested changes
@anstkras, домашку проверил. Как пофиксите или напишите контраргументы (не стесняйтесь спорить аргументированно, я тоже могу ошибаться), упомяните меня через "@RamSaw". У меня, к сожалению, доступа к hwproj нет, поэтому так поступим. Но если увижу на hwproj, что Вы пофиксили, то тоже посмотрю.

2019-02-02 22:43 UTC, RamSaw commented on 2/src/main/java/ru/hse/anstkras/Serializable/Serializable.java
> +public interface Serializable {
Добавьте, пожалуйста, комментарии к интерфейсу и всем методам в нем. В реализующем его классе уже можно будет сослаться на этот комментарий.

2019-02-02 22:43 UTC, RamSaw commented on 2/src/main/java/ru/hse/anstkras/Trie/Trie.java
> +
Зачем тут пустая строка?

2019-02-02 22:43 UTC, RamSaw commented on 2/src/main/java/ru/hse/anstkras/Trie/Trie.java
> +    protected TrieNode root = new TrieNode();
Я бы отказался от protected полей. Вам IDEA, наверное, тоже подсказывала сделать их private. Тут стоит от них отказаться из-за того, что подобные классы могут попасть в какую-нибудь библеотеку, а там от них кто-нибудь отнаследуется и нарушит Ваши инварианты. Понятно, что, наверное, в случае с NULL_ERROR это несильно страшно, но вот с root может сильно все поломать. Можно это посмотреть: https://stackoverflow.com/questions/14684733/final-classes-in-java-which-shouldnt-be-final-or-vice-versa или что-нибудь подобное. Это область, конечно, близка к холивару, но protected root мне не нравится совсем. Вообще делайте как можно уже видимость всегда, так будет легче.

2019-02-02 22:43 UTC, RamSaw commented on 2/src/main/java/ru/hse/anstkras/Trie/Trie.java
> +     * Throws {@code IllegalArgumentException} in case of null argument
Есть специальный тег: @throws IllegalArgumentException. У Вас он не сгенерировался из-за того, что это unchecked exception и оно не указано после ключевого слова throws в объявлении метода. Но Oracle советует даже unchecked в него вставлять: https://www.oracle.com/technetwork/articles/java/index-137868.html.

2019-02-02 22:43 UTC, RamSaw commented on 2/src/main/java/ru/hse/anstkras/Trie/Trie.java
> +
Тоже самое, пустая строка не нужна. Я дальше не буду это писать еще раз, но пофиксите везде, где это есть, пожалуйста.

2019-02-02 22:43 UTC, RamSaw commented on 2/src/main/java/ru/hse/anstkras/Trie/Trie.java
> +        nodes.add(curNode);
С начала этого метода по эту строку duplicate code с кодом из начала метода remove. Надо бы extract method тогда сделать. Вообще чтобы такой код ловить и не париться советую установить Intellij IDEA Proffessional (у Вас видмо community версия). По студенческой подписке, которая делается минут за 15, можно ее бесплатно получить.

2019-02-02 22:43 UTC, RamSaw commented on 2/src/test/java/ru/hse/anstkras/Trie/TrieTest.java
> +    public void addOneStringAndCheckContains() {
assert'a на contains то нет.

2019-02-02 22:43 UTC, RamSaw commented on 2/src/test/java/ru/hse/anstkras/Trie/TrieTest.java
> +public class TrieTest {
Замените все public на package-private (методов тоже касается). Нет же смысла делать тесты публичными, вряд ли их кто-то кроме вас будет запускать.

2019-02-02 22:43 UTC, RamSaw commented on 2/src/test/java/ru/hse/anstkras/Trie/TrieTest.java
> +    void serializeAndDeserializeWith2BytesSymbols() throws IOException {
Тела этого теста и теста serializeAndDeserialize можно в принципе выделить в отдельный метод. Я бы еще добавил тестов на то, что будет если передать null в методы serialize и deserialize, а также что будет при сериализации пустого бора.

2019-02-02 22:43 UTC, RamSaw commented on 2/src/test/java/ru/hse/anstkras/Trie/TrieTest.java
> +        trie = null;
А зачем trie обнулять? У нас же сборщик мусора и заботиться не надо, просто в @BeforeEach будет новый бор присваиваться, а старый потом удалится сборщиком мусора.

2019-02-02 22:43 UTC, RamSaw commented on 2/src/main/java/ru/hse/anstkras/Trie/Trie.java
> +                curNode.next.put(c, newNode);
Наверное установку size = 1 лучше переместить в конструктор. А для добавления ребра у Node лучше сделать специальный метод, повысит читаемость кода.

2019-02-02 22:43 UTC, RamSaw commented on 2/src/main/java/ru/hse/anstkras/Trie/Trie.java
> +                curNode = curNode.next.get(c);
Лучше выделить метод класса Node, название которого бы описывало, что здесь происходит. Вообще есть правило двух точек: если идет цепока обращений через точку, то лучше выделить метод.

2019-02-02 22:43 UTC, RamSaw commented on 2/src/main/java/ru/hse/anstkras/Trie/Trie.java
> +
Опять пустая строка. Там дальше тоже будет, уберите их, пожалуйста.

2019-02-02 22:43 UTC, RamSaw commented on 2/src/main/java/ru/hse/anstkras/Trie/Trie.java
> +     * Throws {@code IllegalArgumentException} in case of null argument
Тоже самое по поводу throws.

2019-02-02 22:43 UTC, RamSaw commented on 2/src/main/java/ru/hse/anstkras/Trie/Trie.java
> +     * @return {@code true} if the element is presented in the trie
{@code true}, до этого Вы не выделяли тегом это. Это уже немного придирки, но давайте какой-то одной нотации придерживаться. Мне кажется проще будет не выделять это тегом, ибо не must have требование.

2019-02-02 22:43 UTC, RamSaw commented on 2/src/main/java/ru/hse/anstkras/Trie/Trie.java
> +        if (element == null) {
Вот эту проверку на параметры можно выделить в отдельный метод, чтобы потом сразу во всех местах пофиксить можно было, к примеру, если Вы захотите использовать checked exception, а не runtime, коим является IllegalStateException.

2019-02-02 22:43 UTC, RamSaw commented on 2/src/main/java/ru/hse/anstkras/Trie/Trie.java
> +            if (curNode.next.containsKey(c)) {
тоже, давайте сделаем метод hasEdge. Это как минимум скроет, что у вас там HashMap'a какая-то лежит и людям читающим класс Trie неважно, как устроена Node. Тут конечно Node это static nested class, но все же.

2019-02-02 22:43 UTC, RamSaw commented on 2/src/main/java/ru/hse/anstkras/Trie/Trie.java
> +    public boolean remove(String element) {
`assertTrue(trie.add("abc"));`
`assertTrue(trie.remove("abc"));`
`assertTrue(trie.add("abc"));`
Падает такой тест, мне кажется проблема в remove.

2019-02-02 22:43 UTC, RamSaw commented on 2/src/main/java/ru/hse/anstkras/Trie/Trie.java
> +    public void serialize(OutputStream out) throws IOException {
Проверка входных аргументов.

2019-02-02 22:43 UTC, RamSaw commented on 2/src/main/java/ru/hse/anstkras/Trie/Trie.java
> +    public void deserialize(InputStream in) throws IOException {
Проверка входных аргументов.

2019-02-02 22:43 UTC, RamSaw commented on 2/src/main/java/ru/hse/anstkras/Trie/Trie.java
> +    protected void serializeNode(TrieNode node, OutputStream out) throws IOException {
Приватным надо делать, IDEA наверняка ругалась. Тоже самое касается deserializeNode.

2019-02-02 22:43 UTC, RamSaw commented on 2/src/main/java/ru/hse/anstkras/Trie/Trie.java
> +        root.countSize();
А почему не сериализовывать поле size? Для экономия памяти? 
Если сериализовывать, то тогда этот метод не нужен будет.

2019-02-02 22:43 UTC, RamSaw commented on 2/src/main/java/ru/hse/anstkras/Trie/Trie.java
> +    protected TrieNode deserializeNode(InputStream in) throws IOException {
Вообще serializeNode и deserializeNode можно запихнуть в класс Node, тогда не будет, к примеру, больших конструкций с точками: node.next.entrySet(). Но если не хотите, можете не делать, класс все-таки вложенный и это не очень критично.

2019-02-02 22:43 UTC, RamSaw commented on 2/src/main/java/ru/hse/anstkras/Trie/Trie.java
> +    protected static class TrieNode {
Очень хорошо, у Вас еще не было вложенных классов, но это правильное решение положить его сюда. Только класс, поля и методы сделайте, пожалуйста, private. Разумеется, кроме перегруженных.

2019-02-02 22:43 UTC, RamSaw commented on 2/src/main/java/ru/hse/anstkras/Trie/Trie.java
> +            if (next.size() != otherNode.next.size()) {
Можно просто: next.equals(otherNode.next)

2019-02-02 22:43 UTC, RamSaw commented on 2/src/main/java/ru/hse/anstkras/Trie/Trie.java
> +            int hashCode = 0;
Можно просто: Objects.hash(next, isTerminal, size). Вообще IDEA может генерить hashCode и equals автоматически.

2019-02-02 22:43 UTC, RamSaw commented on 2/src/main/java/ru/hse/anstkras/Trie/Trie.java
> +        protected int countSize() {
Вообще у этого метода сложное поведение, потому что, после его вызова, изменится состояние всех Nodes в поддереве, что может быть неожиданно. Я бы как минимум написал комментарий к методу или же просто избавился от него (см. выше).

2019-02-08 13:59 UTC, RamSaw requested changes
Неисправлено:
https://github.com/anstkras/Java-Homework/pull/2#discussion_r253278563
https://github.com/anstkras/Java-Homework/pull/2#discussion_r253279463
https://github.com/anstkras/Java-Homework/pull/2#discussion_r253279665

А все остальное хорошо, жду исправлений. Давайте Вы когда исправите, упомяните меня в следующий раз через @, а то может Вы еще собирались исправлять, а я Вам не дал это сделать, начав проверять.

2019-02-08 13:59 UTC, RamSaw commented on 2/src/test/java/ru/hse/anstkras/Trie/TrieTest.java
> +    void remove() {
Название бы получше.

2019-02-09 09:56 UTC, anstkras commented on 2/src/main/java/ru/hse/anstkras/Trie/Trie.java
> +        nodes.add(curNode);
Не очень понятно, как это выделить в один метод, учитывая, что дальше требуется и `curNode`, и `nodes`. И IDEA в данном случае не знает, как делать extract method.

2019-02-09 10:05 UTC, anstkras commented
@RamSaw, оставшиеся замечания доисправляла/прокомментировала.

2019-02-11 15:13 UTC, jzuken commented on 2/src/main/java/ru/hse/anstkras/Trie/Trie.java
> +        TrieNode curNode = root;
а можно не сокращать имена переменных? дальше буду за такое баллы снимать

2019-02-13 08:59 UTC, RamSaw requested changes
@anstkras исправления проверил, все ок. Напишите, пожалуйста, еще тесты отдельно на serialize и deserialize. То есть не только на то, что вместе они дают identity, но еще и на то, что они оба правильно следуют заданному протоколу сериализации бора. Это у всех проблема и мы всех просим писать такие тесты. Прошу прощения, что не сказал об этом сразу же.

2019-02-17 11:54 UTC, anstkras commented
@RamSaw , добавила тесты для serialize и deserialize.

2019-02-17 20:47 UTC, RamSaw approved these changes
Ок, все хорошо. Круто, что нашли улучшение, которого я не заметил. И правда, кучу раз рекурсивно new не стоит вызывать. Передаю слово @jzuken.

2019-02-28 10:07 UTC, jzuken commented on 2/src/main/java/ru/hse/anstkras/Trie/Trie.java
> +     * @return {@code false} if element is already in the
тут бы вполне в одну строку влезло, лучше не плодить строки без необходимости. 100-120 символов -- адекватная граница для современных мониторов

2019-02-28 10:07 UTC, merged

2019-02-28 10:11 UTC, jzuken commented
минус полтора балла за неисправленные замечания, итого 8.5 баллов