Hw3
anstkras/Java-Homework pull request #4
Opened 2019-02-12 14:09 UTC by anstkras

2019-02-12 14:13 UTC, anstkras commented on TreeSet/src/main/java/ru/hse/anstkras/TreeSet/AVLTree.java
> +            if (compare(node.value, e) < 0) {
Код для `lower` и `floor` сильно совпадает, но кажется, что не получится это исправить, не пожертвовав временем работы(например, для `floor` вызывать `contains` и `lower`)

2019-02-24 21:15 UTC, RamSaw requested changes
@anstkras домашку проверил, жду исправлений

2019-02-24 21:15 UTC, RamSaw commented on TreeSet/src/main/java/ru/hse/anstkras/TreeSet/AVLTree.java
> +    public boolean remove(@NotNull Object value) {
Вообще он может быть null.

2019-02-24 21:15 UTC, RamSaw commented on TreeSet/src/main/java/ru/hse/anstkras/TreeSet/AVLTree.java
> +    public boolean contains(@NotNull Object value) {
тоже мб null. Везде вообще мб null, но если компаратор его не поддерживает, то может броситься NPE. См. https://docs.oracle.com/javase/10/docs/api/java/util/TreeSet.html#contains(java.lang.Object)

2019-02-24 21:15 UTC, RamSaw commented on TreeSet/src/main/java/ru/hse/anstkras/TreeSet/AVLTree.java
> +            if (compare(node.value, e) < 0) {
Ну мы же асимптотику не ухудшим. Давайте лучше пожертвуем.

2019-02-24 21:15 UTC, RamSaw commented on TreeSet/src/main/java/ru/hse/anstkras/TreeSet/AVLTree.java
> +    public E higher(@NotNull E e) {
ceiling и higher выражаются через floor и lower. тогда и код не будет повторяться.

2019-02-24 21:15 UTC, RamSaw commented on TreeSet/src/main/java/ru/hse/anstkras/TreeSet/AVLTree.java
> +    private TreeNode<E> firstNode() {
TreeNode ни к чему делать generic. И так уже известно, что он имеет тип E.

2019-02-24 21:15 UTC, RamSaw commented on TreeSet/src/main/java/ru/hse/anstkras/TreeSet/AVLTree.java
> +        T prev() {
обычно у итераторов такого метода нет

2019-02-24 21:15 UTC, RamSaw commented on TreeSet/src/main/java/ru/hse/anstkras/TreeSet/AVLTree.java
> +            return prev();
просто сюда его и вставьте

2019-02-24 21:15 UTC, RamSaw commented on TreeSet/src/test/java/ru/hse/anstkras/TreeSet/AVLTreeTest.java
> +class AVLTreeTest {
Добавьте, пожалуйста, тестов на то, что изменения в descendingSet влекут за собой изменения в обычном Set.

2019-02-24 21:18 UTC, RamSaw commented on TreeSet/src/test/java/ru/hse/anstkras/TreeSet/AVLTreeTest.java
> +class AVLTreeTest {
И на исключения, по типу NoSuchElementException и на то, какое поведение будет, если создать Set с элементами, которые не Comparable.

2019-03-02 13:10 UTC, anstkras commented on TreeSet/src/main/java/ru/hse/anstkras/TreeSet/AVLTree.java
> +    private TreeNode<E> firstNode() {
Почему уже известно? TreeNode - это static nested class.

2019-03-02 16:57 UTC, anstkras commented on TreeSet/src/main/java/ru/hse/anstkras/TreeSet/AVLTree.java
> +    public E higher(@NotNull E e) {
Как можно выразить ceiling и higher через floor и lower?

2019-03-02 16:58 UTC, anstkras commented
@RamSaw , замечания исправлены/прокомментированы.

2019-03-03 20:27 UTC, RamSaw commented on TreeSet/src/main/java/ru/hse/anstkras/TreeSet/AVLTree.java
> +    public E higher(@NotNull E e) {
Ну если у нас reverse order, то вызов floor и lower вернет, на обычном order результат ceiling и higher.

2019-03-03 20:28 UTC, RamSaw commented on TreeSet/src/main/java/ru/hse/anstkras/TreeSet/AVLTree.java
> +    private TreeNode<E> firstNode() {
ну да, вопрос как раз и в том, зачем его static делать.

2019-03-03 20:40 UTC, RamSaw commented on TreeSet/src/main/java/ru/hse/anstkras/TreeSet/AVLTree.java
> +    public E higher(@NotNull E e) {
Ну ладно, и так сойдет, я думаю.

2019-03-03 20:46 UTC, RamSaw requested changes
@anstkras исправления посмотрел, написал новые комментарии.
Не забывайте меня упоминать, когда полностью фиксите замечания.

2019-03-03 20:46 UTC, RamSaw commented on TreeSet/src/test/java/ru/hse/anstkras/TreeSet/AVLTreeTest.java
>          assertEquals("Fsd", tree.first());
Давайте еще проверим, что first и last кидают NoSuchElement на пустом множестве. У Вас это не так, но в оригинальном TreeSet именно такое поведение.

2019-03-03 20:46 UTC, RamSaw commented on TreeSet/src/test/java/ru/hse/anstkras/TreeSet/AVLTreeTest.java
> +    void testTreeSetOfNonComparableElements() {
Давайте еще добавим тестов на то, что будет если передать в remove и contains объект, не являющийся предком E, но при этом remove и contains спокойно отработуют (то есть этот объект умеет все же сравниваться с E).

2019-03-09 18:54 UTC, anstkras commented on TreeSet/src/main/java/ru/hse/anstkras/TreeSet/AVLTree.java
> +    public E higher(@NotNull E e) {
reverse order пользуется реализациями higher и lower для обычного order. Мне такое решение понравилось больше, чем писать один универсальный обход, принимающий параметром isReverse, где придется ставить много ифов.

2019-03-09 19:46 UTC, anstkras commented
@RamSaw , замечания исправлены

2019-03-09 21:34 UTC, RamSaw commented
@anstkras на мой взгляд все ок. Передаю слово @jzuken .

2019-03-13 13:58 UTC, merged